set nocompatible

let base16colorspace=256
set background=dark
colorscheme base16-tomorrow-night

syntax on

if has("autocmd")
  filetype plugin indent on
endif

set autoindent
set backspace=indent,eol,start
set hlsearch
set ignorecase
set incsearch
set number
set ruler
set showcmd
set showmatch
set smartcase
