set nocompatible

let base16colorspace=256
set background=dark
colorscheme base16-tomorrow

set autoindent
set backspace=indent,eol,start
set ignorecase
set incsearch
set nomodeline
set number
set ruler
set showcmd
set showmatch
set smartcase

if has("syntax")
  syntax on
endif

if has("filetype")
  filetype on
  filetype indent on
endif
